//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRITO
    {
        public CARRITO()
        {
            this.DETALLE_CARRITO = new HashSet<DETALLE_CARRITO>();
            this.ENTREGA = new HashSet<ENTREGA>();
        }
    
        public decimal CAR_ID { get; set; }
        public System.DateTime CAR_FECHA { get; set; }
        public string CAR_ESTADO { get; set; }
        public decimal FORMA_PAGO_FOPA_ID { get; set; }
        public decimal CAR_VALOR_NETO { get; set; }
        public decimal CAR_VALOR_IVA { get; set; }
        public decimal CAR_VALOR_DESC { get; set; }
        public decimal CAR_VALOR_BRUTO { get; set; }
        public decimal CLIENTE_CLI_ID { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual ICollection<DETALLE_CARRITO> DETALLE_CARRITO { get; set; }
        public virtual ICollection<ENTREGA> ENTREGA { get; set; }
    }
}
