//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.CARRITO = new HashSet<CARRITO>();
        }
    
        public decimal CLI_ID { get; set; }
        public string CLI_RUT { get; set; }
        public string CLI_PRIMER_NOMBRE { get; set; }
        public string CLI_SEGUNDO_NOMBRE { get; set; }
        public string CLI_PRIMER_APELLIDO { get; set; }
        public string CLI_SEGUNDO_APELLIDO { get; set; }
        public string CLI_EMAIL { get; set; }
        public System.DateTime CLI_FECHA_NACIMIENTO { get; set; }
        public System.DateTime CLI_FECHA_REGISTRO { get; set; }
        public string CLI_ESTADO { get; set; }
        public string CLI_DIRECCION { get; set; }
        public decimal COMUNA_COM_ID { get; set; }
    
        public virtual ICollection<CARRITO> CARRITO { get; set; }
        public virtual COMUNA COMUNA { get; set; }
    }
}
