//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CARRITO
    {
        public short DCARR_LINEA { get; set; }
        public decimal CARRITO_CAR_ID { get; set; }
        public decimal DCARR_PRECIO { get; set; }
        public decimal DCARR_CANTIDAD { get; set; }
        public decimal PRODUCTO_PROD_ID { get; set; }
    
        public virtual CARRITO CARRITO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
