//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTREGA
    {
        public decimal ENT_ID { get; set; }
        public System.DateTime ENT_FECHA_SALIDA { get; set; }
        public System.DateTime ENT_FECHA_ENTREGA_ESTIMADA { get; set; }
        public Nullable<System.DateTime> ENT_FECHA_ENTREGA_REAL { get; set; }
        public Nullable<System.DateTime> ENT_HORA_ENTREGA { get; set; }
        public decimal ESTADO_ENTREGA_EST_ID { get; set; }
        public decimal COMUNA_COM_ID2 { get; set; }
        public decimal COMUNA_COM_ID { get; set; }
        public string ENT_DESCRIPCION { get; set; }
        public decimal CARRITO_CAR_ID { get; set; }
        public string ENT_DIRECCION_ORIGEN { get; set; }
        public string ENT_DIRECCION_DESTINO { get; set; }
    
        public virtual CARRITO CARRITO { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual COMUNA COMUNA1 { get; set; }
        public virtual ESTADO_ENTREGA ESTADO_ENTREGA { get; set; }
    }
}
