//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CARRITO> CARRITO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<DETALLE_CARRITO> DETALLE_CARRITO { get; set; }
        public DbSet<ENTREGA> ENTREGA { get; set; }
        public DbSet<ESTADO_ENTREGA> ESTADO_ENTREGA { get; set; }
        public DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public DbSet<GEOLOCALIZACION> GEOLOCALIZACION { get; set; }
        public DbSet<IMAGEN> IMAGEN { get; set; }
        public DbSet<PERFIL> PERFIL { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PRODUCTOR> PRODUCTOR { get; set; }
        public DbSet<PROVINCIA> PROVINCIA { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<TIPO_IMAGEN> TIPO_IMAGEN { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
    }
}
