//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLE_CARRITO = new HashSet<DETALLE_CARRITO>();
            this.IMAGEN = new HashSet<IMAGEN>();
        }
    
        public decimal PROD_ID { get; set; }
        public string PRO_NOMBRE { get; set; }
        public decimal PROD_CANTIDAD { get; set; }
        public string PROD_DESCRIPCION { get; set; }
        public decimal PROD_PRECIO { get; set; }
        public decimal TIPO_PRODUCTO_TP_ID { get; set; }
        public string PRODUCTOR_PROV_RUT { get; set; }
    
        public virtual ICollection<DETALLE_CARRITO> DETALLE_CARRITO { get; set; }
        public virtual ICollection<IMAGEN> IMAGEN { get; set; }
        public virtual PRODUCTOR PRODUCTOR { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
    }
}
