//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCIA
    {
        public PROVINCIA()
        {
            this.COMUNA = new HashSet<COMUNA>();
        }
    
        public decimal PROVI_ID { get; set; }
        public string PROVI_NOMBRE { get; set; }
        public decimal REGION_REG_ID { get; set; }
    
        public virtual ICollection<COMUNA> COMUNA { get; set; }
        public virtual REGION REGION { get; set; }
    }
}
