//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string USU_EMAIL { get; set; }
        public string USU_PASSWORD { get; set; }
        public decimal PERFIL_PER_ID { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
    }
}
